name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@cyb3rko"
